/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.discos.Disco;
import com.github.britooo.looca.api.group.discos.DiscoGrupo;
import com.github.britooo.looca.api.group.dispositivos.DispositivoUsb;
import com.github.britooo.looca.api.group.dispositivos.DispositivosUsbGrupo;
import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.github.britooo.looca.api.group.sistema.Sistema;
import comunicacao.slack.SlackeandoMetodos;
import conexao.JDBC.Componente;
import java.awt.Color;
import java.sql.ResultSet;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import looca.Coletor;
import conexao.JDBC.Conexao;
import conexao.JDBC.ConfiguracaoComponente;
import conexao.JDBC.Empresa;
import conexao.JDBC.EnviaDados;
import conexao.JDBC.InfoMaquina;
import conexao.JDBC.Maquina;
import conexao.JDBC.Metrica;
import conexao.JDBC.MetricaMouse;
import conexao.JDBC.RegistroAtividade;
import conexao.JDBC.Usb;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import oshi.hardware.UsbDevice;
import java.time.LocalDateTime;

/**
 *
 * @author vitor
 */
public class LoginJframe extends javax.swing.JFrame {

    /**
     * Creates new form LoginJframe
     */
    public LoginJframe() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/assets/logoIc.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bacckground = new javax.swing.JPanel();
        jFundoAzul = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLoginTitulo = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelPatrimonio = new javax.swing.JLabel();
        btnLogar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtPatrimonio = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bacckground.setBackground(new java.awt.Color(255, 255, 255));
        Bacckground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFundoAzul.setBackground(new java.awt.Color(0, 32, 79));
        jFundoAzul.setForeground(new java.awt.Color(255, 255, 255));

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jFundoAzulLayout = new javax.swing.GroupLayout(jFundoAzul);
        jFundoAzul.setLayout(jFundoAzulLayout);
        jFundoAzulLayout.setHorizontalGroup(
            jFundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFundoAzulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLogo)
                .addGap(18, 18, 18))
            .addGroup(jFundoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addContainerGap())
        );
        jFundoAzulLayout.setVerticalGroup(
            jFundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFundoAzulLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLogo)
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Bacckground.add(jFundoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 0, 330, 500));

        jLoginTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLoginTitulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLoginTitulo.setText("Login");
        Bacckground.add(jLoginTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabelSenha.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha");
        Bacckground.add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabelPatrimonio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelPatrimonio.setText("Patrimônio ");
        Bacckground.add(jLabelPatrimonio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        btnLogar.setBackground(new java.awt.Color(0, 25, 61));
        btnLogar.setForeground(new java.awt.Color(255, 255, 255));
        btnLogar.setText("Logar");
        btnLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        Bacckground.add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 340, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Bacckground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 500, 0));

        txtPatrimonio.setCaretColor(new java.awt.Color(0, 32, 79));
        txtPatrimonio.setDisabledTextColor(new java.awt.Color(0, 32, 79));
        txtPatrimonio.setSelectionColor(new java.awt.Color(0, 32, 79));
        Bacckground.add(txtPatrimonio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 340, 35));

        txtSenha.setCaretColor(new java.awt.Color(0, 32, 79));
        txtSenha.setDisabledTextColor(new java.awt.Color(0, 32, 79));
        txtSenha.setSelectionColor(new java.awt.Color(0, 32, 79));
        Bacckground.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 340, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bacckground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bacckground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed

        String patrimonio_digitado = txtPatrimonio.getText();
        String senha_digitada = txtSenha.getText();

        //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
        // Validação Log
        Maquina validMaquina = new Maquina(patrimonio_digitado, senha_digitada);// Adicionado Construtor na classe máquina]
        UsuarioDAO validacaoLog = new UsuarioDAO();// Executa-se a consulta ao banco referente ao método para instanciar objeto Maquina que servirá ara autenticação;

        ResultSet rsusariodaos = validacaoLog.autenticsacaoUsuario(validMaquina);// Nesta linha é instanciado objeto com parâmetros provenientes da consulta com a Azure
        LogTeste log = new LogTeste();

        try {
            log.login(rsusariodaos, rsusariodaos.next());
        } catch (SQLException ex) {
            Logger.getLogger(LoginJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // Objetos JDBC
            Conexao conexao = new Conexao();
            JdbcTemplate conMysql = conexao.getConnection();
            JdbcTemplate conAzure = conexao.getConnectionAzu();

            // Objetos Entidades
            InfoMaquina infoMaquina = new InfoMaquina();
            RegistroAtividade registroAtividade = new RegistroAtividade();
            Usb usb = new Usb();
            Componente componente = new Componente();
            ConfiguracaoComponente configComponente = new ConfiguracaoComponente();
            Metrica metrica = new Metrica();
            MetricaMouse metricaMouse = new MetricaMouse();

            // Objetos  Looca
            Looca looca = new Looca();
            Sistema sistema = looca.getSistema();
            Memoria memoria = looca.getMemoria();
            DiscoGrupo grupoDeDiscos = looca.getGrupoDeDiscos();
            Processador processador = looca.getProcessador();

            String patrimonio_maquina = txtPatrimonio.getText();
            String senha_maquina = txtSenha.getText();

            Maquina maquina = new Maquina(patrimonio_maquina, senha_maquina);// Adicionado Construtor na classe máquina
            SlackeandoMetodos aviso= new SlackeandoMetodos();
            

            UsuarioDAO objUsuarioDAO = new UsuarioDAO();// Executa-se a consulta ao banco referente ao método para instanciar objeto Maquina que servirá ara autenticação;
            ResultSet rsusariodao = objUsuarioDAO.autenticsacaoUsuario(maquina);// Nesta linha é instanciado objeto com parâmetros provenientes da consulta com a Azure

            if (rsusariodao.next()) {
                //lOGADO
                ImageIcon icon = new ImageIcon(getClass().getResource("/assets/verificado.png"));
                JOptionPane.showMessageDialog(null, "Login realizado!",
                        "Seja Bem-Vindo!", JOptionPane.INFORMATION_MESSAGE, icon);

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                //Setando Atributos
                maquina.setIdEmpresa(rsusariodao.getInt("idEmpresa"));
                maquina.setRazaoSocial(rsusariodao.getString("razaoSocial"));
                maquina.setCNPJ(rsusariodao.getString("CNPJ"));
                maquina.setEmail(rsusariodao.getString("email"));
                maquina.setTel(rsusariodao.getString("tel"));

                maquina.setNomeUsuario(rsusariodao.getString("nomeDoUsuario"));
                maquina.setFkEmpresa(rsusariodao.getInt("idEmpresa"));
                maquina.setIdMaquina(rsusariodao.getInt("idMaquina"));

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Tratamento de dados da tabela  InfoMaquina
                // Tamanho Total Disco
                Long tamanhoTotalDisco = grupoDeDiscos.getTamanhoTotal();
                double tamanhoTotalGB = tamanhoTotalDisco != null ? tamanhoTotalDisco / (1024 * 1024 * 1024.0) : 0.0;
                int tamanhoTotalFormatadoDisco = (int) Math.round(tamanhoTotalGB);

                // Tamanho Memoria Total
                Long memoriaTotal01 = looca.getMemoria().getTotal();
                long totalMemory1 = memoriaTotal01 != null ? memoriaTotal01 : 0L; // Verifica se a memória total é nula e atribui 0 em caso afirmativo
                int tamanhoTotalFormatadoMemoria = (int) Math.round((double) totalMemory1 / (1024 * 1024 * 1024));
                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Insert tabela Empresa
                List<Empresa> listadeEmpresa = conMysql.query("select * from Empresa where idEmpresa = ?",
                        new BeanPropertyRowMapper(Empresa.class), rsusariodao.getInt("idEmpresa"));// informações extraídas da consulta sqlserver realizadas em usuario DAO, preenchendo o bean property  com um construtor vazio disponível para receber o objeto específico do servidor.
                if (listadeEmpresa.isEmpty()) {
                    // Inset tabela Empresa
                    conMysql.update("INSERT INTO Empresa (idEmpresa, razaoSocial, CNPJ, email, tel) VALUES (?,?,?,?,?)",
                            maquina.getIdEmpresa(),
                            maquina.getRazaoSocial(),
                            maquina.getCNPJ(),
                            maquina.getEmail(),
                            maquina.getTel());
                }

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Insert tabela Maquina
                List<Maquina> listaDeMaquina1 = conMysql.query("select * from Maquina where idMaquina = ?",
                        new BeanPropertyRowMapper(Maquina.class), rsusariodao.getInt("idMaquina"));
                if (listaDeMaquina1.isEmpty()) {

                    // Inset tabela Maquina
                    conMysql.update("INSERT INTO Maquina (idMaquina, nomeDoUsuario, patrimonio, senha, fkEmpresa) VALUES (?,?,?,?,?)",
                            maquina.getIdMaquina(),
                            maquina.getNomeUsuario(),
                            maquina.getPatrimonio(),
                            maquina.getSenha(),
                            maquina.getFkEmpresa());
                }

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Insert tabela InfoMaquina Local
                List<Maquina> listaDeMaquina = conMysql.query("select * from InfoMaquina where fkMaquina = ?",
                        new BeanPropertyRowMapper(Maquina.class), rsusariodao.getInt("idMaquina"));
                if (listaDeMaquina.isEmpty()) {
                    conMysql.update("insert into InfoMaquina (sistemaoperacional, fabricante, arquitetura, nomeProcessador, capacidadeRam, capacidadeDisco, fkmaquina, fkempresa) values (?,?,?,?,?,?,?,?)",
                            sistema.getSistemaOperacional(),
                            sistema.getFabricante(),
                            sistema.getArquitetura(),
                            processador.getNome(),
                            tamanhoTotalFormatadoMemoria,
                            tamanhoTotalFormatadoDisco,
                            maquina.getIdMaquina(),
                            maquina.getFkEmpresa());
                } else {
                    conMysql.update("update InfoMaquina set sistemaoperacional=?, fabricante=?, arquitetura=?, nomeProcessador=?, capacidadeRam=?, capacidadeDisco=? where fkmaquina=?",
                            sistema.getSistemaOperacional(),
                            sistema.getFabricante(),
                            sistema.getArquitetura(),
                            processador.getNome(),
                            tamanhoTotalFormatadoMemoria,
                            tamanhoTotalFormatadoDisco,
                            maquina.getIdMaquina());

                }

                // Insert tabela InfoMaquina Azure
                List<Maquina> listaDeMaquinaAzure = conAzure.query("select * from InfoMaquina where fkMaquina = ?",
                        new BeanPropertyRowMapper(Maquina.class), rsusariodao.getInt("idMaquina"));
                if (listaDeMaquinaAzure.isEmpty()) {
                    conAzure.update("insert into InfoMaquina (sistemaoperacional, fabricante, arquitetura, nomeProcessador, capacidadeRam, capacidadeDisco, fkmaquina, fkempresa) values (?,?,?,?,?,?,?,?)",
                            sistema.getSistemaOperacional(),
                            sistema.getFabricante(),
                            sistema.getArquitetura(),
                            processador.getNome(),
                            tamanhoTotalFormatadoMemoria,
                            tamanhoTotalFormatadoDisco,
                            maquina.getIdMaquina(),
                            maquina.getFkEmpresa());

                } else {
                    conAzure.update("update InfoMaquina set sistemaoperacional=?, fabricante=?, arquitetura=?, nomeProcessador=?, capacidadeRam=?, capacidadeDisco=? where fkmaquina=?",
                            sistema.getSistemaOperacional(),
                            sistema.getFabricante(),
                            sistema.getArquitetura(),
                            processador.getNome(),
                            tamanhoTotalFormatadoMemoria,
                            tamanhoTotalFormatadoDisco,
                            maquina.getIdMaquina());
                }

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Insert Tabela Usb
                LocalDateTime dataHoraAcesso = LocalDateTime.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

                DispositivosUsbGrupo dispositivos = looca.getDispositivosUsbGrupo();

                List<DispositivoUsb> dispositivosConectados = dispositivos.getDispositivosUsbConectados();

                for (DispositivoUsb dispositivo : dispositivosConectados) {
                    usb.setNome(dispositivo.getNome());
                    usb.setFornecedor(dispositivo.getForncecedor());
                    conMysql.update("INSERT INTO Usb (nome,fornecedor,dataHora,fkmaquina,fkEmpresa) VALUES (?,?,?,?,?)",
                            usb.getNome(),
                            usb.getFornecedor(),
                            dataHoraAcesso,
                            maquina.getIdMaquina(),
                            maquina.getFkEmpresa()
                    );
                    conAzure.update("INSERT INTO Usb (nome,fornecedor,dataHora,fkmaquina,fkEmpresa) VALUES (?,?,?,?,?)",
                            usb.getNome(),
                            usb.getFornecedor(),
                            dataHoraAcesso,
                            maquina.getIdMaquina(),
                            maquina.getFkEmpresa()
                    );
                }

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Insert Tabela RegistroAtividade
                conMysql.update("insert into RegistroAtividade(fkEmpresa, fkMaquina, inicializado) values (?,?,?)",
                        maquina.getFkEmpresa(),
                        maquina.getIdMaquina(),
                        dataHoraAcesso
                );

                conAzure.update("insert into RegistroAtividade(fkEmpresa, fkMaquina, inicializado) values (?,?,?)",
                        maquina.getFkEmpresa(),
                        maquina.getIdMaquina(),
                        dataHoraAcesso
                );
                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Insert Tabela Componente
//                List<Componente> ListaComponente = conMysql.query("select*From Componente  join ConfiguracaoComponente on fkComponente = idComponente where fkMaquina = ?",
//                        new BeanPropertyRowMapper(Maquina.class), rsusariodao.getInt("idMaquina"));
//                if (ListaComponente.isEmpty()) {
//                    //set 1
//                    componente.setTipoCompenente("Disco");
//                    componente.setIdComponente(1);
//
//                    conMysql.update("insert into Componente(idComponente, tipoComponente) values (?,?)",
//                            componente.getIdComponente(),
//                            componente.getTipoCompenente()
//                    );
//
//                    //set 2
//                    componente.setIdComponente(2);
//                    componente.setTipoCompenente("Processador");
//
//                    conMysql.update("insert into Componente(idComponente, tipoComponente) values (?,?)",
//                            componente.getIdComponente(),
//                            componente.getTipoCompenente()
//                    );
//
//                    //set 3
//                    componente.setIdComponente(3);
//                    componente.setTipoCompenente("Memoria");
//
//                    conMysql.update("insert into Componente(idComponente, tipoComponente) values (?,?)",
//                            componente.getIdComponente(),
//                            componente.getTipoCompenente()
//                    );
//                }
//
//                        
//    // Insert Tabela ConfiguracaoComponente 
//                //set CPU
//                componente.setIdComponente(1);
//                configComponente.setUnidadeMedida("GB");
//                conMysql.update("insert into ConfiguracaoComponente(fkMaquina, fkEmpresa, FkComponente,capacidade,unidadeMedida) values (?,?,?,?,?)",
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente(),
//                        tamanhoTotalFormatadoDisco,
//                        configComponente.getUnidadeMedida()
//                );
//                conAzure.update("insert into ConfiguracaoComponente(fkMaquina, fkEmpresa, FkComponente,capacidade,unidadeMedida) values (?,?,?,?,?)",
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente(),
//                        tamanhoTotalFormatadoDisco,
//                        configComponente.getUnidadeMedida()
//                );
//                //Tratando Dados Processador
//                componente.setIdComponente(2);
//
//                Long frequenciaLong = processador.getFrequencia();
//                double frequenciaGHz = frequenciaLong != null ? frequenciaLong / 1e9 : 0.0;
//                int frequenciaInt = (int) Math.round(frequenciaGHz);
//
//                // Set Processador
//                configComponente.setCapacidade(frequenciaInt);
//                configComponente.setUnidadeMedida("GHz");
//                conMysql.update("insert into ConfiguracaoComponente(fkMaquina, fkEmpresa, FkComponente,capacidade,unidadeMedida) values (?,?,?,?,?)",
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente(),
//                        configComponente.getCapacidade(),
//                        configComponente.getUnidadeMedida()
//                );
//                conAzure.update("insert into ConfiguracaoComponente(fkMaquina, fkEmpresa, FkComponente,capacidade,unidadeMedida) values (?,?,?,?,?)",
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente(),
//                        configComponente.getCapacidade(),
//                        configComponente.getUnidadeMedida()
//                );
//                //Tratando Dados Memoria
//                Long memoriaTotal = looca.getMemoria().getTotal();
//                long totalMemory = memoriaTotal != null ? memoriaTotal : 0L; // Verifica se a memória total é nula e atribui 0 em caso afirmativo
//                int memoriaTotalInt = (int) Math.round((double) totalMemory / (1024 * 1024 * 1024));
//
//                // Set Memoria
//                componente.setIdComponente(3);
//                configComponente.setCapacidade(memoriaTotalInt);
//                configComponente.setUnidadeMedida("GB");
//                conMysql.update("insert into ConfiguracaoComponente(fkMaquina, fkEmpresa, FkComponente,capacidade,unidadeMedida) values (?,?,?,?,?)",
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente(),
//                        configComponente.getCapacidade(),
//                        configComponente.getUnidadeMedida()
//                );
//                conAzure.update("insert into ConfiguracaoComponente(fkMaquina, fkEmpresa, FkComponente,capacidade,unidadeMedida) values (?,?,?,?,?)",
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente(),
//                        configComponente.getCapacidade(),
//                        configComponente.getUnidadeMedida()
//                );
//
//                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
////                // Insert Tabela MetricaMouse 
////                conMysql.update("insert into MetricaMouse(codernadaX,codernadaY,dataHora,statusMouse,fkMaquina,fkEmpresa) values (?,?,?,?,?,?)",
////                        metricaMouse.getCordenadaX(),
////                        metricaMouse.getCordenaday(),
////                        metricaMouse.getDataHora(),
////                        metricaMouse.getStatus(),
////                        maquina.getIdMaquina(),
////                        maquina.getFkEmpresa()
////                );
//                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
//                //  Insert Tabela Metrica Disco
//                metrica.setUnidadeMedida("Kbs");
//                componente.setIdComponente(1);
//                List<Disco> discos = grupoDeDiscos.getDiscos();
//                Long discoLeitura;
//
//                for (Disco disco : discos) {
//                    discoLeitura = disco.getBytesDeLeitura();
//                    double discoLeituraDouble = (double) discoLeitura;
//                    discoLeitura = disco.getBytesDeLeitura();
//                    double discoLeituraKB = discoLeitura / 1024.0;
//                    System.out.println(discoLeituraKB);
//
//                    conMysql.update("insert into Metrica(valorUtilizado,unidadeMedida,dataHora,fkMaquina,fkEmpresa, fkComponente) values (?,?,?,?,?,?)",
//                            discoLeituraKB,
//                            metrica.getUnidadeMedida(),
//                            dataHoraAcesso,
//                            maquina.getIdMaquina(),
//                            maquina.getFkEmpresa(),
//                            componente.getIdComponente()
//                    );
//                    break;
//                }
//
//                // Insert Tabela Metrica Processador
//                Double Processador = processador.getUso();
//                metrica.setUnidadeMedida("Gb");
//                componente.setIdComponente(2);
//
//                conMysql.update("insert into Metrica(valorUtilizado,unidadeMedida,dataHora,fkMaquina,fkEmpresa, fkComponente) values (?,?,?,?,?,?)",
//                        Processador,
//                        metrica.getUnidadeMedida(),
//                        dataHoraAcesso,
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente()
//                );
//
//                conAzure.update("insert into Metrica(valorUtilizado,unidadeMedida,dataHora,fkMaquina,fkEmpresa, fkComponente) values (?,?,?,?,?,?)",
//                        Processador,
//                        metrica.getUnidadeMedida(),
//                        dataHoraAcesso,
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente()
//                );
//
//                // Insert Tabela Metrica Memoria
//                long LongMemoriaUso = memoria.getEmUso();
//                double memoriaEmUsoGB = (double) LongMemoriaUso / (1024 * 1024 * 1024);
//
//                metrica.setUnidadeMedida("Gb");
//                componente.setIdComponente(3);
//
//                conMysql.update("insert into Metrica(valorUtilizado,unidadeMedida,dataHora,fkMaquina,fkEmpresa, fkComponente) values (?,?,?,?,?,?)",
//                        memoriaEmUsoGB,
//                        metrica.getUnidadeMedida(),
//                        dataHoraAcesso,
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente()
//                );
//
//                conAzure.update("insert into Metrica(valorUtilizado,unidadeMedida,dataHora,fkMaquina,fkEmpresa, fkComponente) values (?,?,?,?,?,?)",
//                        memoriaEmUsoGB,
//                        metrica.getUnidadeMedida(),
//                        dataHoraAcesso,
//                        maquina.getIdMaquina(),
//                        maquina.getFkEmpresa(),
//                        componente.getIdComponente()
//                );

                //--------------------------------------------------------------------------------------------------------------------------------------------------------------------
                // Selects com Resultados
                // Tabela Maquina
                List< RegistroAtividade> registroAtividades = conMysql.query("select * from RegistroAtividade order by idRegistroUsuario asc",
                        new BeanPropertyRowMapper(RegistroAtividade.class));
                System.out.println(registroAtividades);

                // Tabela InfoMaquina
                List< InfoMaquina> infoMaquinas = conMysql.query("select * from InfoMaquina order by idInfoMaquina asc",
                        new BeanPropertyRowMapper(InfoMaquina.class));
                System.out.println(infoMaquinas);

                //Tabela Maquina e Empresa
                List<Maquina> maquinas = conMysql.query("select * from Maquina join Empresa on fkempresa=idempresa order by idMaquina asc",
                        new BeanPropertyRowMapper(Maquina.class));
                System.out.println(maquinas);
                
//                aviso.notificar();
                EnviaDados inicio = new EnviaDados();
                inicio.iniciarEnvio(maquina.getIdMaquina(),maquina.getFkEmpresa());

            } else {
                // Erro
                ImageIcon icon = new ImageIcon(getClass().getResource("/assets/erro.png"));
                JOptionPane.showMessageDialog(null, "Login Inválido",
                        "Erro", JOptionPane.INFORMATION_MESSAGE, icon);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro");
        }


    }//GEN-LAST:event_btnLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bacckground;
    private javax.swing.JButton btnLogar;
    private javax.swing.JPanel jFundoAzul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPatrimonio;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLoginTitulo;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPatrimonio;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private double bytesToGB(long memoriaEmUso) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
